# Generated by Django 3.1.2 on 2020-11-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Aros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=30)),
                ('tamaño', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('tipoPin', models.IntegerField()),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoaros')),
            ],
        ),
    ]
