# Generated by Django 3.1.2 on 2020-11-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('color', models.CharField(max_length=30)),
                ('tamaño', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('tipoPin', models.CharField(max_length=20)),
                ('tipoforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoaro')),
            ],
        ),
    ]
