# Generated by Django 3.1.2 on 2020-11-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComuna', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='sugerenciaConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreS', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='comunas',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='sugerenciaConsulta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='comuna',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.comunas'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='sugCon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.sugerenciaconsulta'),
        ),
    ]
