# Generated by Django 3.1.2 on 2020-11-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201108_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Mensaje',
            field=models.CharField(max_length=300, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Nombre',
            field=models.CharField(max_length=90, verbose_name='Ingrese su Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='comuna',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.comunas', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='sugCon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.sugerenciaconsulta', verbose_name='Sugerencia o Consulta'),
        ),
    ]
